/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DataModel, Param } from "@senx/discovery-widgets";
export { DataModel, Param } from "@senx/discovery-widgets";
export namespace Components {
    interface Kwh50Line {
        "debug": boolean;
        "export": (type?: "png" | "svg") => Promise<void>;
        "height": number;
        "options": Param | string;
        /**
          * ********************************************************** ********************** Methods **************************** **********************************************************
         */
        "resize": () => Promise<void>;
        "result": DataModel | string;
        "width": number;
    }
}
export interface Kwh50LineCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKwh50LineElement;
}
declare global {
    interface HTMLKwh50LineElementEventMap {
        "draw": void;
    }
    interface HTMLKwh50LineElement extends Components.Kwh50Line, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKwh50LineElementEventMap>(type: K, listener: (this: HTMLKwh50LineElement, ev: Kwh50LineCustomEvent<HTMLKwh50LineElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKwh50LineElementEventMap>(type: K, listener: (this: HTMLKwh50LineElement, ev: Kwh50LineCustomEvent<HTMLKwh50LineElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKwh50LineElement: {
        prototype: HTMLKwh50LineElement;
        new (): HTMLKwh50LineElement;
    };
    interface HTMLElementTagNameMap {
        "kwh50-line": HTMLKwh50LineElement;
    }
}
declare namespace LocalJSX {
    interface Kwh50Line {
        "debug"?: boolean;
        "height"?: number;
        "onDraw"?: (event: Kwh50LineCustomEvent<void>) => void;
        "options"?: Param | string;
        "result"?: DataModel | string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "kwh50-line": Kwh50Line;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kwh50-line": LocalJSX.Kwh50Line & JSXBase.HTMLAttributes<HTMLKwh50LineElement>;
        }
    }
}
